{% set name = "bcolz-zipline" %}
{% set version = "1.2.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/bcolz_zipline-{{ version }}.tar.gz
  sha256: 3081ee3cb80400d2ab3fdc07290a7e1e87d6657bf9ec29544361d5fd0b111da7

build:
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - cython
    - numpy
    - toml
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  commands:
    - python -c "import bcolz; bcolz.test()"
  requires:
    - numpy
    - setuptools

about:
  home: https://pypi.org/project/bcolz-zipline/
  summary: Columnar and compressed data containers.
  license: BSD-3-Clause
  license_file: LICENSES/BCOLZ.txt

extra:
  recipe-maintainers:
    - stefan-jansen
